### ISSUE TITLE
bug somewhere in get_unique_craters.py

### ISSUE THREAD

**Issue by silburt** [silburt/DeepMoon#12]
@cczhu since you changed get_unique_craters.py there is now a bug in there somewhere. I ran a new set of extracting crater distributions and there are tons of nan entries in the long/lat coordinates, e.g. 
```
[        nan         nan  4.65171524]
[       nan        nan  3.4377277]
[        nan         nan  7.02831142]
[        nan         nan  3.58227701]
```
not sure yet at the moment where the problem is, but you might better understand where it could be coming from? My guess is that it has to do with taking ```np.sin``` or ```np.cos``` of a number not in [-1,1] range, but I actually don't know at the moment. If you don't think you have time to look into this then I will. 

It might ultimately be easier for me to look at it since I have the get_unique_craters.py pipeline set up and could just print everything every time a nan shows up....

**Comment by cczhu** [comment]
It probably would be easier for you to check this with your pipeline.  The fastest way to troubleshoot this would be to insert

```
assert lat_deg is not np.nan
assert long_deg is not np.nan
```

right before `return np.column_stack((long_deg, lat_deg, radii_km))` in `estimate_longlatdiamkm`.  If the problem is my function, this will throw an `AssertionError`, which you can use in IPython or Jupyter to interactively debug with (by printing out the values of `lat_deg_firstest`, `latdiff`, etc., to check the problem).

It would actually be good to set up a test in the test suite that's doing what you're checking.  Is it possible to break up your pipeline into individual tests?  (Ideally we wouldn't put yet another bunch of .hdf5 or .csv files into the `tests` folder, but we could if we had to.)

**Comment by silburt** [comment]
@cczhu - looked into this just now and the problem is stemming from when ```latdiff = 0```. I.e. sometimes ```lat_central - lat_deg_firstest = 0``` and this propagates into ```np.sin(np.pi * latdiff / 180.)) = 0```, which blows up ```lat_deg``` and propagates to ```long_deg```. Do you think there's a simple fix you can make?

**Comment by cczhu** [comment]
Ahh, I didn't appreciate that discretization of our positions to 256 x 256 means sometimes a crater's centre will be right at the long/lat centre.  I put a limiter in there taking advantage of the fact that
```
assert (np.pi * latdiff / 180.) / np.sin(np.pi * latdiff / 180.) == 1
```
works if `latdiff` is less than `1e-6`.  See #13.
