### ISSUE TITLE
`pytest test_get_unique_craters.py` returns no detections in (my environment for) Python 3

### ISSUE THREAD

**Issue by cczhu** [silburt/DeepMoon#9]
I ran `pytest test_get_unique_craters.py` in my Python 2 and Python 3 virtualenvs, and in the Python 3 one it `template_match_t2c` returned `N_match == 0` under the `test_extract` test.  Not obvious why this is happening on a quick inspection of the function.

**Comment by silburt** [comment]
Yes, I was just investigating this and figured out the problem, as I was testing as well. Turns out in python 3:
```
zip(*index_r)
```
returns an object and not a list by default. So Changing:
```coords_r = np.asarray(zip(*index_r))```
to 
```coords_r = np.asarray(list(zip(*index_r)))```
fixed the problem for me. @cczhu could you pull from master (I just merged fixed changes) and try again and confirm that you get good results now?

**Comment by cczhu** [comment]
@silburt Works now, thanks for the update!
